name: Frontend CI

on:
  pull_request:
    paths:
      - 'frontend/**'
  push:
    branches: [main]
    paths:
      - 'frontend/**'

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - run: npm ci
      - run: npm run lint
      - run: npm run test
      - run: npm run build

      - name: Configure AWS credentials
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::958085379190:role/todoapp-github-actions-role
          aws-region: us-east-1

      - name: Sync build to S3
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          aws s3 sync ./dist s3://todo-test-frontend-958085379190-us-east-1-an --delete

      - name: Invalidate CloudFront cache
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E286F7R9A7HAZ9 \
            --paths "/*"